site_name: Lập trình hướng đối tượng
site_description: Object Oriented Programming
  
nav:
    - Các chủ đề:
      - Tổng quan về lập trình hướng đối tượng: overview\index.md
      - Nền tảng .NET và ngôn ngữ C#: dotnet-and-csharp\index.md
      - Mô hình hóa hướng đối tượng: object-oriented-modeling\index.md
      - Lớp và đối tượng: classes-and-objects\index.md
      - Thừa kế và đa hình: inheritance\index.md
      - Phát triển ứng dụng GUI với .NET và C#: gui-development\index.md
      - Thực hành: labs\index.md
    - Giảng viên: author\about.md 

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

extra_css:
  - css/extra.css