site_name: Lập trình hướng đối tượng
site_description: Object Oriented Programming
site_author: Hung Nguyen

repo_url: https://github.com/nd-hung/oop
edit_uri: tree/main/docs

copyright: Copyright &copy; 2023 <a href="https://nd-hung.github.io/">Hung Nguyen</a>


nav:
    - Các chủ đề:
      - Tổng quan về lập trình hướng đối tượng: topics\overview\README.md
      - Nền tảng .NET và ngôn ngữ C#: topics\dotnet-and-csharp\README.md
      - Mô hình hóa hướng đối tượng: topics\object-oriented-modeling\README.md
      - Lớp và đối tượng: topics\classes-and-objects\README.md
      - Thừa kế: topics\inheritance\README.md
      - Đa hình: topics\polymorphism\README.md
      - Phát triển ứng dụng GUI với .NET và C#: topics\gui-development\README.md
      - Thực hành: labs\README.md
    - Giảng viên: author\about.md 

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
        - content.action.view

extra_css:
  - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - def_list
    - tables
